# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.rbi.com:
  peer0.org0.rbi.com:
  peer0.org1.rbi.com:
  peer0.org20rbi.com:

networks:
  pcr:

services:
  ca-lender.rbi.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-lender
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.lender.rbi.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA_LENDER_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.lender.rbi.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CA_LENDER_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/lender.rbi.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_lender
    networks:
      - rbi

  ca-borrower.rbi.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-borrower
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.borrower.rbi.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA_BORROWER_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.borrower.rbi.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CA_BORROWER_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/borrower.rbi.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_lender
    networks:
      - rbi

  ca-org0.rbi.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org0
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org0.rbi.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA_ORG0_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org0.rbi.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CA_ORG0_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org0.rbi.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_lender
    networks:
      - rbi

  ca-org1.rbi.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.rbi.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA_ORG1_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.rbi.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CA_ORG1_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org1.rbi.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_lender
    networks:
      - rbi

  ca-org2.rbi.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.rbi.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA_ORG2_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "11054:11054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.rbi.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${CA_ORG2_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.rbi.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_lender
    networks:
      - rbi



  orderer.rbi.com:
    container_name: orderer.rbi.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/msp/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/rbi.com/orderers/orderer.rbi.com/:/etc/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/rbi.com/orderers/orderer.rbi.com/tls/:/var/hyperledger/orderer/tls
    networks:
      - basic

  peer0.org0.rbi.com:
    container_name: peer0.org0.rbi.com

    environment:
      - CORE_PEER_ID=peer0.org0.rbi.com
      - CORE_PEER_ADDRESS=peer0.org0.rbi.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org0.rbi.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org0.rbi.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org0.rbi.com:7051
      - CORE_PEER_LOCALMSPID=Org0MSP
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_pcr
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org0.rbi.com/peers/peer0.org0.rbi.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org0.rbi.com/peers/peer0.org0.rbi.com/tls:/etc/hyperledger/fabric/tls

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - pcr

  peer0.org1.rbi.com:
    container_name: peer0.org1.rbi.com

    environment:
      - CORE_PEER_ID=peer0.org1.rbi.com
      - CORE_PEER_ADDRESS=peer0.org1.rbi.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.rbi.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.rbi.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.rbi.com:8051
      - CORE_PEER_LOCALMSPID=Org0MSP
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_pcr
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.rbi.com/peers/peer0.org2.rbi.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.rbi.com/peers/peer0.org2.rbi.com/tls:/etc/hyperledger/fabric/tls

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 8051:8051
    networks:
      - pcr

  peer0.org2.rbi.com:
    container_name: peer0.org2.rbi.com

    environment:
      - CORE_PEER_ID=peer0.org2.rbi.com
      - CORE_PEER_ADDRESS=peer0.org2.rbi.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.rbi.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      # - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org0.rbi.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.rbi.com:9051
      - CORE_PEER_LOCALMSPID=Org0MSP
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_pcr
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.rbi.com/peers/peer0.org2.rbi.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/org2.rbi.com/peers/peer0.org2.rbi.com/tls:/etc/hyperledger/fabric/tls

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
    networks:
      - pcr
